/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package task3;

//import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   // @Test void appHasAGreeting() {
     //   App classUnderTest = new App();
       // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
       @ParameterizedTest
       @CsvSource({
          "1,2,3,3",
          "4,5,6,6",
          "5,8,7,8"
          })

        

     void maxTest(int a, int b ,int c,int e) {
       // Calculation a1 = new Calculation();
        assertEquals(e,Calculation.findMax(a, b, c));}

        @ParameterizedTest
        @CsvSource({
          "1,2,3,1",
          "4,5,6,4",
          "5,8,7,5"
         })
    


     void minTest(int a, int b ,int c,int e) {
        //Calculation a1 = new Calculation();
        assertEquals(e,Calculation.findMin(a, b, c));}
        @ParameterizedTest
        @CsvSource({
          "0,1,2,1",
          "1,2,3,2",
          "4,1,10,4"
        })
    

     void MiddleValueTest(int a, int b ,int c,int e) {
      // Calculation a1 = new Calculation();
        assertEquals(e,Calculation.findMiddleValue(a, b, c));}


        @ParameterizedTest
        @CsvSource({
          "0,1,2,1",
          "1,2,3,2",
          "9,2,10,7"})
    

     void AverageTest(int a, int b ,int c,double e) {
       // Calculation a1 = new Calculation();
        assertEquals(e,Calculation.findAverage(a, b, c));
     }

        }
        













